// source: config/tx_filter_config.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var common_birdsnest_pb = require('../common/birdsnest_pb.js');
goog.object.extend(proto, common_birdsnest_pb);
goog.exportSymbol('proto.config.TxFilterConfig', null, global);
goog.exportSymbol('proto.config.TxFilterType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.config.TxFilterConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.config.TxFilterConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.config.TxFilterConfig.displayName = 'proto.config.TxFilterConfig';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.config.TxFilterConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.config.TxFilterConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.config.TxFilterConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.config.TxFilterConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    birdsNest: (f = msg.getBirdsNest()) && common_birdsnest_pb.BirdsNestConfig.toObject(includeInstance, f),
    shardingBirdsNest: (f = msg.getShardingBirdsNest()) && common_birdsnest_pb.ShardingBirdsNestConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.config.TxFilterConfig}
 */
proto.config.TxFilterConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.config.TxFilterConfig;
  return proto.config.TxFilterConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.config.TxFilterConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.config.TxFilterConfig}
 */
proto.config.TxFilterConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.config.TxFilterType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new common_birdsnest_pb.BirdsNestConfig;
      reader.readMessage(value,common_birdsnest_pb.BirdsNestConfig.deserializeBinaryFromReader);
      msg.setBirdsNest(value);
      break;
    case 3:
      var value = new common_birdsnest_pb.ShardingBirdsNestConfig;
      reader.readMessage(value,common_birdsnest_pb.ShardingBirdsNestConfig.deserializeBinaryFromReader);
      msg.setShardingBirdsNest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.config.TxFilterConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.config.TxFilterConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.config.TxFilterConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.config.TxFilterConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getBirdsNest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_birdsnest_pb.BirdsNestConfig.serializeBinaryToWriter
    );
  }
  f = message.getShardingBirdsNest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_birdsnest_pb.ShardingBirdsNestConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional TxFilterType type = 1;
 * @return {!proto.config.TxFilterType}
 */
proto.config.TxFilterConfig.prototype.getType = function() {
  return /** @type {!proto.config.TxFilterType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.config.TxFilterType} value
 * @return {!proto.config.TxFilterConfig} returns this
 */
proto.config.TxFilterConfig.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional common.BirdsNestConfig birds_nest = 2;
 * @return {?proto.common.BirdsNestConfig}
 */
proto.config.TxFilterConfig.prototype.getBirdsNest = function() {
  return /** @type{?proto.common.BirdsNestConfig} */ (
    jspb.Message.getWrapperField(this, common_birdsnest_pb.BirdsNestConfig, 2));
};


/**
 * @param {?proto.common.BirdsNestConfig|undefined} value
 * @return {!proto.config.TxFilterConfig} returns this
*/
proto.config.TxFilterConfig.prototype.setBirdsNest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.config.TxFilterConfig} returns this
 */
proto.config.TxFilterConfig.prototype.clearBirdsNest = function() {
  return this.setBirdsNest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.config.TxFilterConfig.prototype.hasBirdsNest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional common.ShardingBirdsNestConfig sharding_birds_nest = 3;
 * @return {?proto.common.ShardingBirdsNestConfig}
 */
proto.config.TxFilterConfig.prototype.getShardingBirdsNest = function() {
  return /** @type{?proto.common.ShardingBirdsNestConfig} */ (
    jspb.Message.getWrapperField(this, common_birdsnest_pb.ShardingBirdsNestConfig, 3));
};


/**
 * @param {?proto.common.ShardingBirdsNestConfig|undefined} value
 * @return {!proto.config.TxFilterConfig} returns this
*/
proto.config.TxFilterConfig.prototype.setShardingBirdsNest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.config.TxFilterConfig} returns this
 */
proto.config.TxFilterConfig.prototype.clearShardingBirdsNest = function() {
  return this.setShardingBirdsNest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.config.TxFilterConfig.prototype.hasShardingBirdsNest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.config.TxFilterType = {
  NONE: 0,
  BIRDSNEST: 1,
  MAP: 2,
  SHARDINGBIRDSNEST: 3
};

goog.object.extend(exports, proto.config);
